name = "fringe-scraper"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[browser]
binding = "MYBROWSER"

[env.production]
name = "fringe-scraper"

[env.staging]
name = "fringe-scraper-staging"